---
- name: CLOUD VIP - Update the repository cache and update package "keelalived" to latest version using default release squeeze-backport
  apt:
    name: keepalived
    state: latest
    # default_release: squeeze-backports
    update_cache: yes

- name: ANSIBLE ROUTER - A Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file_path }}"
    mode: "0640"
  notify:
      - reload keepalived
